# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-16 21:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=70)),
                ('action_type', models.CharField(blank=True, choices=[('01', 'Free action'), ('02', 'Simple action'), ('03', 'Complex action'), ('04', 'Variable action'), ('05', 'Interruption')], default='', max_length=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ActionEffect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=70)),
                ('value', models.IntegerField(default=0)),
                ('impacted_object', models.CharField(default=None, max_length=70)),
                ('impacted_field', models.CharField(default=None, max_length=70)),
                ('parent_action', models.ManyToManyField(to='persomaker.Action')),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='character')),
                ('name', models.CharField(max_length=70)),
                ('description', models.CharField(blank=True, max_length=2000)),
                ('ethnicity', models.CharField(blank=True, max_length=70)),
                ('age', models.IntegerField(default=0)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unknown')], default='U', max_length=1)),
                ('karma', models.IntegerField(default=0)),
                ('nuyen', models.IntegerField(default=0)),
                ('credibility', models.IntegerField(default=0)),
                ('notoriety', models.IntegerField(default=0)),
                ('awareness', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CharacterModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persomaker.Character')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterObj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_equiped', models.BooleanField(default=False)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persomaker.Character')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=0)),
                ('levelmax', models.IntegerField(default=0)),
                ('order', models.IntegerField(default=0)),
                ('karma_cost', models.IntegerField(default=0)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persomaker.Character')),
            ],
        ),
        migrations.CreateModel(
            name='Modifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=70)),
                ('value', models.IntegerField(default=0)),
                ('character', models.ManyToManyField(blank=True, default=None, to='persomaker.Character')),
                ('impacted_object', models.ManyToManyField(blank=True, default=None, to='persomaker.CharacterObj')),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=70)),
                ('description', models.TextField(blank=True, max_length=5000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='module')),
                ('page', models.IntegerField(blank=True, default=0)),
                ('rulebook', models.CharField(blank=True, max_length=70)),
                ('module_bundle', models.CharField(choices=[('0', 'Metatype'), ('2', 'Nationality'), ('3', 'Formative years'), ('4', 'Teen years'), ('5', 'Further education'), ('6', 'Real life'), ('1', 'Talent'), ('7', 'Options')], default='', max_length=1)),
                ('karma_cost', models.CharField(blank=True, max_length=70)),
                ('options', models.ManyToManyField(blank=True, related_name='_module_options_+', to='persomaker.Module')),
            ],
        ),
        migrations.CreateModel(
            name='ModuleSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=0)),
                ('levelmax', models.IntegerField(default=0)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persomaker.Module')),
            ],
        ),
        migrations.CreateModel(
            name='Obj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=70)),
                ('description', models.CharField(blank=True, max_length=5000)),
                ('category', models.CharField(blank=True, choices=[('01', 'Weapon'), ('02', 'Armor'), ('03', 'Commlink')], default='', max_length=2, null=True)),
                ('authorized_actions', models.ManyToManyField(to='persomaker.Action')),
            ],
        ),
        migrations.CreateModel(
            name='ObjStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0)),
                ('obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persomaker.Obj')),
            ],
        ),
        migrations.CreateModel(
            name='Quality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=70)),
                ('karma_cost', models.IntegerField(default=0)),
                ('quality_type', models.CharField(blank=True, choices=[('01', 'Quality'), ('02', 'Default')], default='', max_length=2, null=True)),
                ('page', models.IntegerField(blank=True, default=0)),
                ('rulebook', models.CharField(blank=True, max_length=70)),
                ('description', models.CharField(blank=True, max_length=5000, null=True)),
                ('character', models.ManyToManyField(blank=True, default=None, to='persomaker.Character')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('slug', models.SlugField(blank=True)),
                ('abstract', models.CharField(blank=True, max_length=70, null=True)),
                ('description', models.CharField(blank=True, max_length=5000, null=True)),
                ('page', models.IntegerField(blank=True, default=0, null=True)),
                ('rulebook', models.CharField(blank=True, max_length=70, null=True)),
                ('skillset_choice', models.CharField(blank=True, choices=[('94', 'Calculated'), ('95', 'Groupskill'), ('96', 'Active skill'), ('98', 'Language'), ('99', 'Attribute'), ('90', 'Academic knowledge'), ('91', 'Interests knowledge'), ('92', 'Professional knowledge'), ('93', 'Street knowledge')], default='', max_length=2, null=True)),
                ('context', models.CharField(blank=True, max_length=500, null=True)),
                ('default', models.NullBooleanField(default=None)),
                ('attribute', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skill_attribute', to='persomaker.Skill')),
                ('limit', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skill_limit', to='persomaker.Skill')),
                ('skillgroup', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skill_skillgroup', to='persomaker.Skill')),
            ],
        ),
        migrations.CreateModel(
            name='SkillSpecialisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('skill', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='persomaker.Skill')),
            ],
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=70)),
                ('description', models.CharField(blank=True, max_length=5000)),
            ],
        ),
        migrations.AddField(
            model_name='objstat',
            name='stat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persomaker.Stat'),
        ),
        migrations.AddField(
            model_name='obj',
            name='skill_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='persomaker.Skill'),
        ),
        migrations.AddField(
            model_name='obj',
            name='stats',
            field=models.ManyToManyField(related_name='stats', through='persomaker.ObjStat', to='persomaker.Stat'),
        ),
        migrations.AddField(
            model_name='moduleskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persomaker.Skill'),
        ),
        migrations.AddField(
            model_name='moduleskill',
            name='specialisations',
            field=models.ManyToManyField(blank=True, default=None, to='persomaker.SkillSpecialisation'),
        ),
        migrations.AddField(
            model_name='module',
            name='qualities',
            field=models.ManyToManyField(blank=True, default=None, to='persomaker.Quality'),
        ),
        migrations.AddField(
            model_name='module',
            name='skills',
            field=models.ManyToManyField(related_name='skills', through='persomaker.ModuleSkill', to='persomaker.Skill'),
        ),
        migrations.AddField(
            model_name='modifier',
            name='impacted_skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persomaker.Skill'),
        ),
        migrations.AddField(
            model_name='characterskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persomaker.Skill'),
        ),
        migrations.AddField(
            model_name='characterskill',
            name='specialisations',
            field=models.ManyToManyField(blank=True, default=None, to='persomaker.SkillSpecialisation'),
        ),
        migrations.AddField(
            model_name='characterobj',
            name='obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persomaker.Obj'),
        ),
        migrations.AddField(
            model_name='charactermodule',
            name='charactermoduleoption',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='charactermoduleoption', to='persomaker.Module'),
        ),
        migrations.AddField(
            model_name='charactermodule',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persomaker.Module'),
        ),
        migrations.AddField(
            model_name='character',
            name='inventory',
            field=models.ManyToManyField(related_name='inventory', through='persomaker.CharacterObj', to='persomaker.Obj'),
        ),
        migrations.AddField(
            model_name='character',
            name='modules',
            field=models.ManyToManyField(related_name='modules', through='persomaker.CharacterModule', to='persomaker.Module'),
        ),
        migrations.AddField(
            model_name='character',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='character',
            name='skills',
            field=models.ManyToManyField(related_name='characters', through='persomaker.CharacterSkill', to='persomaker.Skill'),
        ),
        migrations.AlterUniqueTogether(
            name='characterskill',
            unique_together=set([('character', 'skill')]),
        ),
        migrations.AlterUniqueTogether(
            name='charactermodule',
            unique_together=set([('character', 'module')]),
        ),
    ]
