# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-04 11:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('description', models.CharField(blank=True, max_length=2000)),
                ('ethnicity', models.CharField(blank=True, max_length=70)),
                ('age', models.IntegerField(default=0)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unknown')], default='U', max_length=1)),
                ('karma', models.IntegerField(default=0)),
                ('nuyen', models.IntegerField(default=0)),
                ('credibility', models.IntegerField(default=0)),
                ('notoriety', models.IntegerField(default=0)),
                ('awareness', models.IntegerField(default=0)),
                ('initiative_ar', models.IntegerField(default=0)),
                ('initiative_coldsim', models.IntegerField(default=0)),
                ('initiative_hotsim', models.IntegerField(default=0)),
                ('initiative_physical', models.IntegerField(default=0)),
                ('initiative_astral', models.IntegerField(default=0)),
                ('limit_mental', models.IntegerField(default=0)),
                ('limit_physical', models.IntegerField(default=0)),
                ('limit_social', models.IntegerField(default=0)),
                ('condition_physical', models.IntegerField(default=0)),
                ('condition_stun', models.IntegerField(default=0)),
                ('condition_overflow', models.IntegerField(default=0)),
                ('living_personna_attack', models.IntegerField(default=0)),
                ('living_personna_dataprocessing', models.IntegerField(default=0)),
                ('living_personna_devicerating', models.IntegerField(default=0)),
                ('living_personna_firewall', models.IntegerField(default=0)),
                ('living_personna_sleeze', models.IntegerField(default=0)),
                ('attribute_skill_composure', models.IntegerField(default=0)),
                ('attribute_skill_judgeintention', models.IntegerField(default=0)),
                ('attribute_skill_lifting', models.IntegerField(default=0)),
                ('attribute_skill_memory', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CharacterModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persomaker.Character')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=0)),
                ('levelmax', models.IntegerField(default=0)),
                ('order', models.IntegerField(default=0)),
                ('karma_cost', models.IntegerField(default=0)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persomaker.Character')),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=70)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('page', models.IntegerField(blank=True, default=0)),
                ('rulebook', models.CharField(blank=True, max_length=70)),
                ('module_bundle', models.CharField(choices=[('1', 'Metatype'), ('2', 'Nationality'), ('3', 'Formative years'), ('4', 'Teen years'), ('5', 'Further education'), ('6', 'Real life'), ('7', 'Talent')], default='', max_length=1)),
                ('karma_cost', models.CharField(blank=True, max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='ModuleSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=0)),
                ('levelmax', models.IntegerField(default=0)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persomaker.Module')),
            ],
        ),
        migrations.CreateModel(
            name='Quality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('abstract', models.CharField(blank=True, max_length=70)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('page', models.IntegerField(blank=True, default=0)),
                ('rulebook', models.CharField(blank=True, max_length=70)),
                ('skillset_choice', models.CharField(blank=True, choices=[('01', 'Acting'), ('02', 'Athletics'), ('03', 'Biotech'), ('04', 'Close combat'), ('05', 'Conjuring'), ('06', 'Cracking'), ('08', 'Electronics'), ('09', 'Enchanting'), ('10', 'Engineering'), ('11', 'Firearms'), ('12', 'Influence'), ('13', 'Outdoors'), ('14', 'Sorcery'), ('15', 'Stealth'), ('16', 'Tasking'), ('99', 'Attribute')], default='', max_length=2, null=True)),
                ('context', models.CharField(blank=True, max_length=70)),
                ('default', models.NullBooleanField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='moduleskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persomaker.Skill'),
        ),
        migrations.AddField(
            model_name='module',
            name='skills',
            field=models.ManyToManyField(related_name='skills', through='persomaker.ModuleSkill', to='persomaker.Skill'),
        ),
        migrations.AddField(
            model_name='characterskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persomaker.Skill'),
        ),
        migrations.AddField(
            model_name='charactermodule',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persomaker.Module'),
        ),
        migrations.AddField(
            model_name='character',
            name='modules',
            field=models.ManyToManyField(related_name='modules', through='persomaker.CharacterModule', to='persomaker.Module'),
        ),
        migrations.AddField(
            model_name='character',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='character',
            name='skills',
            field=models.ManyToManyField(related_name='characters', through='persomaker.CharacterSkill', to='persomaker.Skill'),
        ),
        migrations.AlterUniqueTogether(
            name='characterskill',
            unique_together=set([('character', 'skill')]),
        ),
    ]
