# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 09:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persomaker', '0002_auto_20170131_0936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='characterskill',
            name='name',
        ),
        migrations.AddField(
            model_name='skill',
            name='attribute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='persomaker.Skill'),
        ),
        migrations.AddField(
            model_name='skill',
            name='context',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AddField(
            model_name='skill',
            name='page',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='skill',
            name='rulebook',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AlterField(
            model_name='skill',
            name='description',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AlterField(
            model_name='skill',
            name='group',
            field=models.CharField(blank=True, max_length=70),
        ),
    ]
