# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-20 11:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0009_circle_circlecontacts'),
        ('persomaker', '0002_auto_20170616_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='campaign',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='usermanagement.Circle'),
        ),
    ]
