# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persomaker', '0003_auto_20170131_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='default',
            field=models.NullBooleanField(default=None),
        ),
    ]
