# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-12 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0002_auto_20170612_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='invitation_accepted',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='invitation_send',
            field=models.NullBooleanField(),
        ),
    ]
