# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-13 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0004_auto_20170613_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='circle',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
