# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-20 09:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0005_circle_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Player',
            new_name='Contact',
        ),
        migrations.RemoveField(
            model_name='circle',
            name='players',
        ),
    ]
