# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-20 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0006_auto_20170620_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='circle',
            name='circlecontacts',
            field=models.ManyToManyField(to='usermanagement.Contact'),
        ),
    ]
