# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-20 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0009_circle_circlecontacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='circle',
            name='image',
            field=models.ImageField(null=True, upload_to='circle'),
        ),
    ]
