# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-22 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0011_auto_20170622_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='circle',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
