# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('created_date', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField()),
                ('schedule_date', models.DateField()),
                ('closed', models.BooleanField(default=False)),
            ],
        ),
    ]
